repository:
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: false
  default_branch: main
  delete_branch_on_merge: true
  description: yet another way to paint a cat
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  homepage: https://github.com/montchr/nix-base16-schemes
  name: nix-base16-schemes
  private: false
